### ISSUE TITLE
Create Integration Tests using Tescontainers

### ISSUE THREAD

**Issue by S-Tim** [holunda-io/polyflow-examples#215]
It would be beneficial to an integration test setup that could utilize Testcontainers. For example the single node MariaDB scenario would benefit from such a setup That way it could use the same migration scripts in the tests as it does in when run normally.

An example for a mariab test profile could look like this:
`application-mariadb.yml`
```
spring:
  datasource:
    url: jdbc:h2:mem:public;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=create schema if not exists PUBLIC;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
```

Unfortunately using the MariaDB compatibility mode of H2 is currently not possible with the Camunda initialization scripts because it seems that the syntax for creating indices is not fully supported.
